default: &default
  adapter: postgresql
  encoding: unicode
  username: test
  password: rails


development:
  adapter: postgresql
  encoding: unicode
  database: my_app_development
  pool:
  host: localhost
  username: test
  password: rails

test:
  adapter: postgresql
  encoding: unicode
  database: my_app_test
  pool:
  username: test
  password: rails

production:
  adapter: postgresql
  encoding: unicode
  database: my_app_production
  pool:
  username: test
  password: rails