default: &default
  adapter: postgresql
  encoding: unicode
  username: 
  password: 


development:
  adapter: postgresql
  encoding: unicode
  database: my_app_development
  pool:
  host: localhost
  username: 
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: my_app_test
  pool:
  username: 
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: my_app_production
  pool:
  username: 
  password: 
  